project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - slides.qmd
    - assignments.qmd
    - assignment1.qmd
             
website:
  title: ""
  search: false  
  navbar:
    search: false
    title: BUSI 721
    file: index.qmd
    right:
      
      - text: Slides
        file: slides.qmd
      - text: Assignments
        file: assignments.qmd
      - text: Solutions
        href: https://github.com/kerryback/busi721/tree/main/solutions
      - text: Notebooks
        href: https://github.com/kerryback/busi721/tree/main/notebooks
      - text: Learn Investments Dashboard
        href: https://learn-investments.rice-business.org
      
        
format: 
  html:
    theme: cosmo
    scss: styles.css
    link-external-newwindow: true
    
   



